### ISSUE TITLE
Buffer not flushed correctly.

### ISSUE THREAD

**Issue by LuckyResistor** [FEEprojects/plantower#1]
The library uses the following code to flush the buffer before a new read is started:

`self.serial.flush() #Flush any data in the buffer`

IMO the correct code should be:

`self.serial.reset_input_buffer()`

The function `flush()` just makes sure everything gets written. I assume the author of the code would make sure a current reading is made and no past readings from the buffer are used.

**Comment by pjb304** [comment]
Hi LuckyResistor,

Many thanks for raising this issue, you are indeed correct. Your fix and a new release will be published shortly.
